function a1() {
	document.getElementById('div1').style.display = 'block';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a2() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'block';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a3() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'block';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a4() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'block';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a5() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'block';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a6() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'block';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a7() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'block';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a8() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'block';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a9() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'block';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a10() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'block';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a11() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'block';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a12() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'block';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'none';
}
function a13() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'block';
	document.getElementById('div14').style.display = 'none';
}
function a14() {
	document.getElementById('div1').style.display = 'none';
	document.getElementById('div2').style.display = 'none';
	document.getElementById('div3').style.display = 'none';
	document.getElementById('div4').style.display = 'none';
	document.getElementById('div5').style.display = 'none';
	document.getElementById('div6').style.display = 'none';
	document.getElementById('div7').style.display = 'none';
	document.getElementById('div8').style.display = 'none';
	document.getElementById('div9').style.display = 'none';
	document.getElementById('div10').style.display = 'none';
	document.getElementById('div11').style.display = 'none';
	document.getElementById('div12').style.display = 'none';
	document.getElementById('div13').style.display = 'none';
	document.getElementById('div14').style.display = 'block';
}
